name: Test code
on: [push]
jobs:
  unit-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: './api/package-lock.json'
    - run: |
          cd api
          npm install
          npm test
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: './api/package-lock.json'
    - run: |
        cd api
        npm install
        npm coverage
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: './api/package-lock.json'
    - name: Install API dependencies and run API
      run: |
        cd api
        npm install
        npx prisma db push
        npx prisma db seed
        npm run dev &
    - name: Install client dependencies and run client
      run: |
        cd client
        npm install
        npm run dev &
    - name: Run Cypress tests
      run: |
        npm ci
        npx cypress run