name: Tests and coverage
on: [push]
jobs:
  tests-coverage:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: './api/package-lock.json'

    - name: Run back-end
      run: |
        cd api
        npm install
        npx prisma db push
        npx prisma db seed
        npm run dev &
    - name: Run front-end
      run: |
        cd client
        npm install
        npm run dev &
    - name: Run unit tests
      run: |
          cd api
          npm run coverage
    - name: Run E2E tests
      run: |
        cd client
        npx cypress run
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}